branches:
  only:
  - master
  - deploy

language: python
# make it explicit that we favor the new container-based travis workers
sudo: false
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
env:
  global:
     - OMP_NUM_THREADS=4
     - OPENBLAS_NUM_THREADS=4
  matrix:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Precise 12.04
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    # This environment tests the oldest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.6" INSTALL_MKL="false"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
      NUMPY_VERSION="1.10.2" SCIPY_VERSION="0.16.1"

cache: apt

install: source install.sh

script: bash test_script.sh

after_success:
  - travis-sphinx --branches=master,deploy deploy
