dist: trusty
branches:
  only:
  - master
  - deploy

language: python - "2.7"

before_install:
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

install:
  - pip install numpy scipy scikit-learn matplotlib numpy PIL
  - pip install sphinx==1.4
  - pip install --user travis-sphinx

cache: conda
script:
  - cp -r translate/* doc
  - cd doc
  - travis-sphinx --source=. --nowarn build
  - cd target/doc/build
  - echo "sklearn.lzjqsdd.com" > CNAME
  - cd ../../..

after_success:
  - travis-sphinx --branches=master,deploy deploy
